counter_type: fast
initial_capacity: 32768
logging:
  level: INFO
  loggers:
    jgrillo: INFO
metrics:
  frequency: 1 minute
  reporters:
    - type: console
server:
  maxThreads: 1024
  maxQueuedRequests: 2048
  requestLog:
    appenders:
      - type: console
        queueSize: 2048
